package com.codingwithsalman.jotjive.core.presentation.designsystem.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color

val Stressed25 = Color(0xFFF9EFEF)
val Stressed35 = Color(0xFFE9C5C5)
val Stressed80 = Color(0xFFDE3A3A)
val Stressed95 = Color(0xFF6B0303)

val Sad25 = Color(0xFFEFF4F8)
val Sad35 = Color(0xFFC5D8E9)
val Sad80 = Color(0xFF3A8EDE)
val Sad95 = Color(0xFF004585)

val Neutral25 = Color(0xFFEEF7F3)
val Neutral35 = Color(0xFFB9DDCB)
val Neutral80 = Color(0xFF41B278)
val Neutral95 = Color(0xFF0A5F33)

val Peaceful25 = Color(0xFFF6F2F5)
val Peaceful35 = Color(0xFFE1CEDB)
val Peaceful80 = Color(0xFFBE3294)
val Peaceful95 = Color(0xFF6C044D)

val Excited25 = Color(0xFFF5F2EF)
val Excited35 = Color(0xFFDDD2C8)
val Excited80 = Color(0xFFDB6C0B)
val Excited95 = Color(0xFF723602)

val MoodPrimary25 = Color(0xFFEEF0FF)
val MoodPrimary35 = Color(0xFFBAC6E9)
val MoodPrimary80 = Color(0xFF00419C)

val Primary10 = Color(0xFF001945)
val Primary30 = Color(0xFF004CB4)
val Primary40 = Color(0xFF0057CC)
val Primary50 = Color(0xFF1F70F5)
val Primary60 = Color(0xFF578CFF)
val Primary90 = Color(0xFFD9E2FF)
val Primary95 = Color(0xFFEEF0FF)
val Primary100 = Color(0xFFFFFFFF)

val Secondary30 = Color(0xFF3B4663)
val Secondary50 = Color(0xFF6B7796)
val Secondary70 = Color(0xFF9FABCD)
val Secondary80 = Color(0xFFBAC6E9)
val Secondary90 = Color(0xFFD9E2FF)
val Secondary95 = Color(0xFFEEF0FF)

val NeutralVariant10 = Color(0xFF191A20)
val NeutralVariant30 = Color(0xFF40434F)
val NeutralVariant50 = Color(0xFF6C7085)
val NeutralVariant80 = Color(0xFFC1C3CE)
val NeutralVariant90 = Color(0xFFE0E1E7)
val NeutralVariant99 = Color(0xFFFCFDFE)

val Error20 = Color(0xFF680014)
val Error95 = Color(0xFFFFEDEC)
val Error100 = Color(0xFFFFFFFF)

val Gray = Color(0xFF8E8E93)
val Gray2 = Color(0xFFAEAEB2)
val Gray3 = Color(0xFFC7C7CC)
val Gray4 = Color(0xFFD1D1D6)
val Gray5 = Color(0xFFE5E5EA)
val Gray6 = Color(0xFFF2F2F7)

val RedOrange = Color(0xffffab91)
val RedPink = Color(0xfff48fb1)
val BabyBlue = Color(0xff81deea)
val Violet = Color(0xffcf94da)
val LightGreen = Color(0xffe7ed9b)

val ColorScheme.bgGradient: Brush
    get() = Brush.verticalGradient(
        listOf(
            Secondary90.copy(alpha = 0.4f),
            Secondary95.copy(alpha = 0.4f),
        )
    )

val ColorScheme.buttonGradient: Brush
    get() = Brush.verticalGradient(
        listOf(
            primaryLight.copy(alpha = 0.4f),
            primaryLight.copy(alpha = 0.5f),
        )
    )

val ColorScheme.buttonGradientPressed: Brush
    get() = Brush.verticalGradient(
        listOf(
            primaryLight.copy(alpha = 0.4f),
            primaryLight.copy(alpha = 0.6f),
        )
    )

val ColorScheme.primary90: Color
    get() = primaryLight.copy(
        alpha = 0.1f
    )

val ColorScheme.primary95: Color
    get() = primaryLight.copy(
        alpha = 0.05f
    )

val ColorScheme.secondary95: Color
    get() = secondaryLight.copy(
        alpha = 0.05f
    )

val ColorScheme.secondary70: Color
    get() = secondaryLight.copy(
        0.3f
    )

/**/
val primaryLight = Color(0xFF6F5D0E)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFBE187)
val onPrimaryContainerLight = Color(0xFF544600)
val secondaryLight = Color(0xFF675E40)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFEFE2BC)
val onSecondaryContainerLight = Color(0xFF4E462A)
val tertiaryLight = Color(0xFF44664D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFC6ECCD)
val onTertiaryContainerLight = Color(0xFF2D4E37)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF8EF)
val onBackgroundLight = Color(0xFF1E1B13)
val surfaceLight = Color(0xFFFFF8EF)
val onSurfaceLight = Color(0xFF1E1B13)
val surfaceVariantLight = Color(0xFFEAE2CF)
val onSurfaceVariantLight = Color(0xFF4B4639)
val outlineLight = Color(0xFF7C7767)
val outlineVariantLight = Color(0xFFCEC6B4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF333027)
val inverseOnSurfaceLight = Color(0xFFF7F0E2)
val inversePrimaryLight = Color(0xFFDDC56E)
val surfaceDimLight = Color(0xFFE0D9CC)
val surfaceBrightLight = Color(0xFFFFF8EF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFAF3E5)
val surfaceContainerLight = Color(0xFFF4EDDF)
val surfaceContainerHighLight = Color(0xFFEFE7DA)
val surfaceContainerHighestLight = Color(0xFFE9E2D4)

val primaryLightMediumContrast = Color(0xFF413500)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF7F6C1D)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF3D361B)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF766D4D)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF1C3D27)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF53755B)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF8EF)
val onBackgroundLightMediumContrast = Color(0xFF1E1B13)
val surfaceLightMediumContrast = Color(0xFFFFF8EF)
val onSurfaceLightMediumContrast = Color(0xFF131109)
val surfaceVariantLightMediumContrast = Color(0xFFEAE2CF)
val onSurfaceVariantLightMediumContrast = Color(0xFF3A3629)
val outlineLightMediumContrast = Color(0xFF575244)
val outlineVariantLightMediumContrast = Color(0xFF726D5E)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF333027)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF7F0E2)
val inversePrimaryLightMediumContrast = Color(0xFFDDC56E)
val surfaceDimLightMediumContrast = Color(0xFFCCC6B9)
val surfaceBrightLightMediumContrast = Color(0xFFFFF8EF)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFFAF3E5)
val surfaceContainerLightMediumContrast = Color(0xFFEFE7DA)
val surfaceContainerHighLightMediumContrast = Color(0xFFE3DCCF)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD8D1C4)

val primaryLightHighContrast = Color(0xFF362B00)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF574800)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF332C12)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF51492C)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF11321E)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF2F5039)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF8EF)
val onBackgroundLightHighContrast = Color(0xFF1E1B13)
val surfaceLightHighContrast = Color(0xFFFFF8EF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFEAE2CF)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF302C20)
val outlineVariantLightHighContrast = Color(0xFF4E493B)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF333027)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFDDC56E)
val surfaceDimLightHighContrast = Color(0xFFBEB8AB)
val surfaceBrightLightHighContrast = Color(0xFFFFF8EF)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF7F0E2)
val surfaceContainerLightHighContrast = Color(0xFFE9E2D4)
val surfaceContainerHighLightHighContrast = Color(0xFFDBD4C6)
val surfaceContainerHighestLightHighContrast = Color(0xFFCCC6B9)

val primaryDark = Color(0xFFDDC56E)
val onPrimaryDark = Color(0xFF3A3000)
val primaryContainerDark = Color(0xFF544600)
val onPrimaryContainerDark = Color(0xFFFBE187)
val secondaryDark = Color(0xFFD2C6A1)
val onSecondaryDark = Color(0xFF373016)
val secondaryContainerDark = Color(0xFF4E462A)
val onSecondaryContainerDark = Color(0xFFEFE2BC)
val tertiaryDark = Color(0xFFAAD0B1)
val onTertiaryDark = Color(0xFF163722)
val tertiaryContainerDark = Color(0xFF2D4E37)
val onTertiaryContainerDark = Color(0xFFC6ECCD)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF16130B)
val onBackgroundDark = Color(0xFFE9E2D4)
val surfaceDark = Color(0xFF16130B)
val onSurfaceDark = Color(0xFFE9E2D4)
val surfaceVariantDark = Color(0xFF4B4639)
val onSurfaceVariantDark = Color(0xFFCEC6B4)
val outlineDark = Color(0xFF979080)
val outlineVariantDark = Color(0xFF4B4639)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE9E2D4)
val inverseOnSurfaceDark = Color(0xFF333027)
val inversePrimaryDark = Color(0xFF6F5D0E)
val surfaceDimDark = Color(0xFF16130B)
val surfaceBrightDark = Color(0xFF3C392F)
val surfaceContainerLowestDark = Color(0xFF100E07)
val surfaceContainerLowDark = Color(0xFF1E1B13)
val surfaceContainerDark = Color(0xFF221F17)
val surfaceContainerHighDark = Color(0xFF2D2A21)
val surfaceContainerHighestDark = Color(0xFF38352B)

val primaryDarkMediumContrast = Color(0xFFF4DB81)
val onPrimaryDarkMediumContrast = Color(0xFF2E2500)
val primaryContainerDarkMediumContrast = Color(0xFFA5903E)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFE9DCB6)
val onSecondaryDarkMediumContrast = Color(0xFF2C250C)
val secondaryContainerDarkMediumContrast = Color(0xFF9B906F)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFC0E6C7)
val onTertiaryDarkMediumContrast = Color(0xFF092C17)
val tertiaryContainerDarkMediumContrast = Color(0xFF76997E)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF16130B)
val onBackgroundDarkMediumContrast = Color(0xFFE9E2D4)
val surfaceDarkMediumContrast = Color(0xFF16130B)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF4B4639)
val onSurfaceVariantDarkMediumContrast = Color(0xFFE4DCC9)
val outlineDarkMediumContrast = Color(0xFFB9B1A0)
val outlineVariantDarkMediumContrast = Color(0xFF969080)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE9E2D4)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2D2A21)
val inversePrimaryDarkMediumContrast = Color(0xFF564700)
val surfaceDimDarkMediumContrast = Color(0xFF16130B)
val surfaceBrightDarkMediumContrast = Color(0xFF48443A)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF090703)
val surfaceContainerLowDarkMediumContrast = Color(0xFF201D15)
val surfaceContainerDarkMediumContrast = Color(0xFF2B281F)
val surfaceContainerHighDarkMediumContrast = Color(0xFF363229)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF413D34)

val primaryDarkHighContrast = Color(0xFFFFEFC0)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFD9C26A)
val onPrimaryContainerDarkHighContrast = Color(0xFF0F0B00)
val secondaryDarkHighContrast = Color(0xFFFDEFC8)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFCEC29D)
val onSecondaryContainerDarkHighContrast = Color(0xFF0F0B00)
val tertiaryDarkHighContrast = Color(0xFFD3FADA)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFA6CCAE)
val onTertiaryContainerDarkHighContrast = Color(0xFF000F04)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF16130B)
val onBackgroundDarkHighContrast = Color(0xFFE9E2D4)
val surfaceDarkHighContrast = Color(0xFF16130B)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF4B4639)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFF8EFDC)
val outlineVariantDarkHighContrast = Color(0xFFCAC2B0)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE9E2D4)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF564700)
val surfaceDimDarkHighContrast = Color(0xFF16130B)
val surfaceBrightDarkHighContrast = Color(0xFF545046)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF221F17)
val surfaceContainerDarkHighContrast = Color(0xFF333027)
val surfaceContainerHighDarkHighContrast = Color(0xFF3F3B32)
val surfaceContainerHighestDarkHighContrast = Color(0xFF4A463D)